sonar.projectKey=carolina-cepeda_Carbon_Tracker_Service
sonar.organization=carolina-cepeda
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.db,**/migrations/**,**/reports/**