name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --only-binary :all: -r requirements.txt
          pip install --only-binary :all: pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
